stage: local
accountId: ""
region: ""
acmCertificateArn: ""
vpcId: ""
subnetId:
  - ""
securityGroupId:
  - ""

logLevel: "DEBUG"
websiteUrl: ""

databaseUrl: ""
databaseSchema: ""
databaseUsername: ""
databasePassword: ""
