stage: local
accountId: ""
region: us-east-1
acmCertificateArn: ""
vpcId: ""
subnetId:
  - ""
securityGroupId:
  - ""

logLevel: DEBUG
websiteUrl: "http://localhost:3001/site/0.2.0"

databaseUrl: ""
databaseSchema: ""
databaseUsername: ""
databasePassword: ""
