stage: prod
accountId: ""
region: us-east-1
acmCertificateArn: ""
vpcId: ""
subnetId:
  - ""
securityGroupId:
  - ""

logLevel: INFO
websiteUrl: 

databaseUrl: ""
databaseSchema: ""
databaseUsername: ""
databasePassword: ""
