# Post Config File

id: "" # post s3 path - Leave Blank
name: "" # post display title
idName: "" # post is without s3 path
summary: "" # post summary display text
htmlFile: "post.html"
primaryImageFile: "post-logo.png"
primaryImageThumbnail: "post-logo-alt.png"

author:
  name: "Preston Frazier" # author display name
  username: "prestonfrazier" # author system id

createdDate: "" # Post created date - Leave Blank
updatedDate: "" # Post most recent updated date - Leave Blank

tags: # tags defining the post
  - ""
  - ""

# Post Dynamic value options
# $$_domain_$$ : replaced with site domain name
